# Generated by Django 4.0.5 on 2024-11-03 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_comment21_comment22'),
    ]

    operations = [
        migrations.DeleteModel(
            name='comment',
        ),
        migrations.DeleteModel(
            name='comment1',
        ),
        migrations.DeleteModel(
            name='comment10',
        ),
        migrations.DeleteModel(
            name='comment11',
        ),
        migrations.DeleteModel(
            name='comment12',
        ),
        migrations.DeleteModel(
            name='comment13',
        ),
        migrations.DeleteModel(
            name='comment14',
        ),
        migrations.DeleteModel(
            name='comment15',
        ),
        migrations.DeleteModel(
            name='comment16',
        ),
        migrations.DeleteModel(
            name='comment17',
        ),
        migrations.DeleteModel(
            name='comment18',
        ),
        migrations.DeleteModel(
            name='comment19',
        ),
        migrations.DeleteModel(
            name='comment2',
        ),
        migrations.DeleteModel(
            name='comment20',
        ),
        migrations.DeleteModel(
            name='comment21',
        ),
        migrations.DeleteModel(
            name='comment22',
        ),
        migrations.DeleteModel(
            name='comment3',
        ),
        migrations.DeleteModel(
            name='comment4',
        ),
        migrations.DeleteModel(
            name='comment5',
        ),
        migrations.DeleteModel(
            name='comment6',
        ),
        migrations.DeleteModel(
            name='comment7',
        ),
        migrations.DeleteModel(
            name='comment8',
        ),
        migrations.DeleteModel(
            name='comment9',
        ),
    ]
